# Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Language and timezone settings
lang: en
timezone: Africa/Cairo  # Adjust based on your preferred timezone

# SEO Settings
title: MavBoy's Blog  # Customize the main title
tagline: Exploring Cybersecurity and Tech Insights  # Customize the subtitle
description: >-
  Technical blog focused on cybersecurity research, red teaming, and hacking insights.

# Website URL, especially for GitHub Pages
url: "https://MavBoy.github.io"

# Social Links and Author Information
github:
  username: MavBoy  # Your GitHub username

twitter:
  username: mavric1337  # Your Twitter handle without the '@'

social:
  name: Mohamed Eletreby
  email: mavricboy@gmail.com
  links:
    - https://x.com/mavric1337
    - https://github.com/MavBoy
    - https://www.linkedin.com/in/0xmaverick/

# Site Verification (optional for analytics)
webmaster_verifications:
  google: # Google verification code if used
  bing: # Bing verification code if used

# Web Analytics (optional if using)
analytics:
  google:
    id:  # Google Analytics ID if used
  goatcounter:
    id: # GoatCounter ID if used

# Page views settings
pageviews:
  provider: goatcounter  # Choose provider, optional

# Color Scheme Preference
theme_mode: dark  # Options: light | dark (or leave blank to follow system settings)

# Optional CDN settings for media resources
cdn:  # Example: 'https://cdn.example.com'

# Sidebar Avatar (optional)
avatar: /assets/images/avatar.png  # Path to your profile picture

# Social Preview Image for SEO
social_preview_image: /assets/images/preview.png  # Image path for social sharing

# Global Table of Contents (TOC) switch
toc: true  # Display TOC by default in posts

# Comments (optional if using Disqus, Utterances, or Giscus)
comments:
  provider: disqus  # Options: disqus | utterances | giscus
  disqus:
    shortname: # Your Disqus shortname, if applicable

# Offline Caching and PWA Configuration
pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:  # Paths you want to exclude from caching

# Pagination
paginate: 10  # Number of posts per page

# Base URL for Jekyll site
baseurl: ""  # Leave blank for GitHub Pages root

# Advanced Syntax and Parsing Options
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

# Enable archives for tags and categories
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
